let addHomeButton1 = document.getElementById("add-homepoints-btn1")
let addHomeButton2 = document.getElementById("add-homepoints-btn2")
let addHomeButton3 = document.getElementById("add-homepoints-btn3")
let addGuestButton1 = document.getElementById("add-guestpoints-btn1")
let addGuestButton2 = document.getElementById("add-guestpoints-btn2")
let addGuestButton3 = document.getElementById("add-guestpoints-btn3")